<script setup>
import { ref } from "vue";
const hidden = ref(false);

const openModal = () => (hidden.value = true);
const closeModal = () => (hidden.value = false);
</script>

<template>
  <div>
    <button
      class="absolute bottom-4 left-4 mr-2 py-2.5 px-5 bg-green-700 z-10 rounded-md text-white cursor-pointer hover:bg-green-800 border-solid border-2 border-green-700 hover:border-green-500"
      @click="openModal"
    >
      Help
    </button>

    <div
      v-if="hidden"
      class="fixed w-screen h-screen z-20 bg-gray-700 bg-opacity-80 flex flex-col justify-center items-center"
    >
      <div
        class="modal-box bg-white flex flex-col justify-center items-start w-auto p-5 rounded-lg"
      >
        <div class="modal-title flex flex-row w-full justify-between pb-3">
          <p class="font-bold">Commands for The Trumpbot</p>
          <button
            type="button"
            class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center"
            @click="closeModal"
          >
            <svg
              aria-hidden="true"
              class="w-5 h-5"
              fill="currentColor"
              viewBox="0 0 20 20"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                fill-rule="evenodd"
                d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                clip-rule="evenodd"
              ></path>
            </svg>
            <span class="sr-only">Close modal</span>
          </button>
        </div>
        <div class="modal-text max-w-xl">
          <ul>
            <li class="py-2">
              <p>
                <span class="italic">!help</span> → The Trumpbot tells you about
                his topics.
              </p>
            </li>
            <li class="py-2">
              <p>
                <span class="italic">!fake</span> → Once The Trumpbot has
                answered your question, you can react with
                <span class="italic">!fake</span> if you think this is a fake
                tweet generated by The Trumpbot.
              </p>
            </li>
            <li class="py-2">
              <p>
                <span class="italic">!real</span> → Once The Trumpbot has
                answered your question, you can react with
                <span class="italic">!real</span> if you think this is a real
                tweet from
                <a
                  class="underline hover:text-green-700"
                  href="https://twitter.com/realdonaldtrump"
                  rel="noreferrer nofollow"
                  target="_blank"
                  >@realDonaldTrump</a
                >.
              </p>
            </li>
          </ul>
        </div>
        <div class="modal-button mt-5 self-center">
          <button
            type="button"
            class="text-white bg-green-700 hover:bg-green-800 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 border-solid border-2 border-green-700 hover:border-green-500"
            @click="closeModal"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped></style>

<div>
  
  
  
</div>
